repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: pytest-integration-tests
        name: Run integration tests
        entry: bash tests/utils/test_runners/pre-commit-tests.sh
        language: system
        pass_filenames: false
        always_run: true
